// ─────────────────────────────────────────────────────────────────────────────
//  Digitales Softwarehandbuch — Inhalte
//  Pflege-Konvention: Bei jeder neuen Funktion den passenden Abschnitt hier
//  ergänzen/aktualisieren (siehe CLAUDE.md). Die „Aktualisierungen"-Liste im
//  Handbuch wird automatisch aus der Git-Historie erzeugt (scripts/gen-changelog).
// ─────────────────────────────────────────────────────────────────────────────
export const HANDBUCH = [
  {
    app: 'Allgemein & Anmeldung',
    icon: '🔑',
    sections: [
      { title: 'Anmeldung mit Name + PIN', keywords: ['login', 'anmelden', 'pin', 'passwort', 'stadt-code', 'code'],
        text: 'Alle Apps nutzen dieselbe Anmeldung: Name (Vor- und Nachname) und 6-stellige PIN eingeben — die richtige Stadt wird automatisch gefunden.\n• Das Feld „Stadt-Code" ist optional und nur nötig, falls derselbe Name mit gleicher PIN in mehreren Städten existiert.\n• Administratoren können sich alternativ per E-Mail und Passwort anmelden (Link „Admin-Anmeldung" unter dem Formular).' },
      { title: 'PIN vergessen / Konto gesperrt', keywords: ['gesperrt', 'sperre', 'fehlversuche', 'pin vergessen', 'lockout'],
        text: 'Nach 5 falschen PIN-Eingaben wird das Konto für 15 Minuten gesperrt — danach einfach erneut versuchen.\nEine neue PIN vergibt der Administrator im Desktop-Planer unter Admin → Benutzer („PIN setzen").' },
      { title: 'Rollen & Berechtigungen', keywords: ['rolle', 'rechte', 'berechtigung', 'admin', 'planer', 'fahrer', 'erfasser', 'lesezugriff', 'readonly'],
        text: 'Jede Person hat eine Rolle, die bestimmt, welche Apps und Module sichtbar sind und ob Änderungen erlaubt sind.\n• Standard-Rollen: Administrator (alles), Planer (planen/bearbeiten), Erfasser (Erfassungs-App), Fahrer (Fahrer-App), Nur-Lesen.\n• Rollen sind stadtscharf: Jede Stadt pflegt ihren eigenen Rollenkatalog unter Admin → Benutzer → Rollen — Änderungen wirken nur im eigenen Mandanten.' },
      { title: 'Mandanten / Städte', keywords: ['mandant', 'stadt', 'orgid', 'mehrere städte', 'stadtwechsel'],
        text: 'Die Software ist mandantenfähig: Jede Stadt sieht ausschließlich ihre eigenen Daten (Objekte, Touren, Personen, Einstellungen).\nStadt-spezifisch sind u. a.: Stadt-Code, KI-Analyse-Modus, Routing-API-Key, WMS-Kartenebenen, Rollen & Module sowie die Personenverwaltung.' },
      { title: 'Datenstandort & Datenschutz', keywords: ['dsgvo', 'datenschutz', 'frankfurt', 'region', 'server', 'speicherort', 'datenschutzhinweise', 'hinweise'],
        text: 'Datenbank, Dateispeicher (Fotos), Serverfunktionen und auch die KI-Auswertung (Gemini) laufen in Frankfurt (Google Cloud, Region europe-west3).\nPINs werden ausschließlich als Hash gespeichert; Fahrer-Logins laufen über eine geschützte Serverfunktion. Es gibt kein Tracking und keine Werbe-Cookies.\nDie vollständigen Datenschutzhinweise (Art. 13 DSGVO) sind auf jeder Anmeldeseite verlinkt und unter /datenschutz.html erreichbar.' },
    ],
  },
  {
    app: 'Desktop-Planer',
    icon: '🖥️',
    sections: [
      { title: 'Projekt öffnen & wechseln', keywords: ['projekt', 'öffnen', 'wechseln', 'stadt'],
        text: 'Nach der Anmeldung erscheint die Projektliste der eigenen Stadt (Superadmin: aller Städte). Projekt anklicken → die Karte öffnet sich und zoomt automatisch auf das Stadtgebiet.\nZurück zur Projektwahl über das Avatar-Menü oben rechts.' },
      { imgs:[{src:'/handbuch/desktop-karte.jpg',cap:'Karte mit Tour-Markern, Legende und Objektliste (Demodaten)'}], title: 'Karte: Marker & Tour-Auswahl', keywords: ['karte', 'marker', 'tour anzeigen', 'mehrfachauswahl', 'gelb', 'zähler', 'legende'],
        text: 'Jedes Objekt erscheint als Marker in der Farbe seiner Tour. Über die Legende rechts lassen sich einzelne oder mehrere Touren einblenden; „Unverplant" zeigt Objekte ohne Tour.\n• Jede Tour-Zeile zeigt rechts die Gesamtzeit; der Pfeil klappt die Details auf (Fahrt-/Tätigkeitszeit mit Balken, Strecke, Objektanzahl).\n• Der Kennzahlen-Block unter der Tourliste zeigt für die aktive Tour Strecke, Fahrt, Tätigkeit und Gesamt.\n• Route berechnen: Rechtsklick auf die Karte → „Route berechnen" (aktive Tour) oder „Alle Routen berechnen".\n• Gehört ein Objekt mehreren gleichzeitig angezeigten Touren an, wird der Marker gelb.\n• Der orangene Zähler am Marker zeigt die Anzahl der Tourzuordnungen (über den Karten-Button abschaltbar).\n• Bei genau einer aktiven Tour zeigen die Marker die Reihenfolge-Nummer der Route.' },
      { title: 'Karte: Buttons & Filter', keywords: ['filter', 'einpassen', 'zoom', 'eigenschaften-filter', 'karte einpassen'],
        text: 'Die Buttons oben links auf der Karte:\n• Karte einpassen — zoomt auf alle Objekte der Stadt.\n• Filter — Eigenschaften-Filter (Stadtteil, Art, Zustand, Bedarf …), wirkt auf Karte und Liste.\n• Planen — startet den Zuweisungs-Modus (siehe „Objekte zu Touren zuweisen").\n• Routen ein/aus, Tour-Zähler ein/aus.' },
      { title: 'Objekte zu Touren zuweisen (Planen & Lasso)', keywords: ['planen', 'lasso', 'zuweisen', 'zuordnung', 'auswahl', 'mehrere objekte'],
        text: '„Planen" auf der Karte aktivieren, Ziel-Tour wählen, dann:\n• Einzelklick auf Objekte — weist das Objekt der Tour zu (erneuter Klick entfernt).\n• Lasso-Symbol aktivieren und einen Bereich umfahren — alle Objekte darin werden zugewiesen.\nEin Objekt kann mehreren Touren angehören (z. B. Sommer-/Sondertour). Rechtsklick auf einen Marker zeigt das Tour-Kontextmenü.' },
      { imgs:[{src:'/handbuch/desktop-detail.jpg',cap:'Objekt-Detail mit Stammdaten, Pflege und Tour-Zuordnung'}], title: 'Objekt-Detail & Bearbeiten', keywords: ['detail', 'bearbeiten', 'zustand', 'bedarf', 'notiz', 'verlauf', 'historie', 'position setzen'],
        text: 'Klick auf einen Marker oder Listeneintrag öffnet das Detail-Panel: Stammdaten, Zustand/Bedarf (direkt änderbar), Tour-Zuordnung (Mehrfachauswahl), Notiz und Fotos.\n• Reiter „Verlauf" zeigt alle Meldungen; Einträge sind editier- und löschbar.\n• „Bearbeiten" öffnet die vollständige Bearbeitungsmaske; „Position setzen" platziert ein Objekt ohne GPS per Kartenklick.\n• Objekte können archiviert (inaktiv) und reaktiviert werden.' },
      { title: 'Dokumente am Objekt', keywords: ['dokument', 'datei', 'pdf', 'gutachten', 'hochladen', 'upload', 'link', 'anhang', 'word', 'excel'],
        text: 'Im Objekt-Detail und im Formular „Objekt bearbeiten" lassen sich Dokumente am Objekt ablegen (Bereich „Dokumente"); dort sind auch die Fotos des Objekts sichtbar:\n• „📎 Datei hochladen" — PDF, Word, Excel, Bilder oder Text vom PC hochladen (bis 20 MB je Datei, mehrere auf einmal möglich). Die Dateien werden sicher in Frankfurt gespeichert und sind nur für die eigene Stadt sichtbar.\n• „🔗 Link hinzufügen" — Verweis auf ein Dokument in einer externen Ablage (z. B. DMS/SharePoint, https-Adresse).\nKlick auf einen Eintrag öffnet das Dokument in einem neuen Tab; × entfernt es (hochgeladene Dateien werden dabei endgültig gelöscht). Nur-Lesen-Rollen sehen die Liste, können aber nichts ändern.' },
      { title: 'Fotos am Objekt', keywords: ['foto', 'bild', 'galerie', 'lightbox', 'löschen', 'original'],
        text: 'Im Objekt-Detail erscheinen alle in der Erfassungs-App aufgenommenen Fotos als Galerie. Klick auf ein Foto öffnet die Großansicht:\n• Blättern mit ‹ › oder Pfeiltasten, Schließen mit ×/Esc.\n• „Original ↗" öffnet das Bild in voller Auflösung.\n• „Löschen" entfernt das Foto endgültig (nicht für Nur-Lesen-Rollen).' },
      { imgs:[{src:'/handbuch/desktop-baeume.jpg',cap:'Objekte-Tabelle mit Suche und Filtern'}], title: 'Objekte-Tabelle & Suche', keywords: ['tabelle', 'objekte', 'liste', 'suche', 'kein gps', 'inaktiv'],
        text: 'Ansicht „Objekte" zeigt alle Objekte als Tabelle mit Suche (Name, Stadtteil, Objekt-ID …).\n• Filter „Kein GPS" zeigt Objekte ohne Koordinaten.\n• Inaktive (archivierte) Objekte lassen sich einblenden.\n• Klick auf eine Zeile springt zur Karte, „Bearbeiten" öffnet die Maske.' },
      { title: 'Arten-Stammdaten (Typ/Art)', keywords: ['arten', 'art', 'typ', 'stammdaten', 'zusammenführen', 'umbenennen', 'dropdown'],
        text: 'In der Ansicht „Objekte" → Reiter „Typ/Art" werden alle vorkommenden Arten als Stammdaten-Liste gepflegt:\n• Umbenennen, Zusammenführen (Duplikate bereinigen — Objekte werden mit umgehängt) und manuelles Anlegen.\n• Die gepflegte Liste erscheint als Auswahl-Dropdown in der Bearbeitungsmaske.' },
      { title: 'Excel-Import', keywords: ['import', 'excel', 'xlsx', 'koordinaten', 'utm', 'etrs89', 'epsg', 'spalten'],
        text: 'Admin → Import: Excel-Datei mit Spalten in dieser Reihenfolge: Anlage/Straße, Stadtteil, Art, Objektnummer, Jahr, Pflanzzeitpunkt, Notiz, Koordinate 1, Koordinate 2.\n• Koordinaten werden automatisch erkannt: Dezimalgrad (z. B. 49,97325 / 8,45188) ODER ETRS89/UTM (z. B. 460696,461 / 5535800,63) — UTM wird automatisch umgerechnet, die Spaltenreihenfolge ist egal.\n• Vor dem Import zeigt eine Vorschau-Karte die Lage aller Punkte; vertauschte Koordinaten lassen sich per Schalter korrigieren.' },
      { imgs:[{src:'/handbuch/desktop-touren.jpg',cap:'Touren-Übersicht mit Fortschritt und Routenfunktionen'}], title: 'Touren anlegen & verwalten', keywords: ['tour', 'anlegen', 'farbe', 'fahrer zuweisen', 'status', 'löschen'],
        text: 'Ansicht „Touren": Tour anlegen mit Name und Farbe; Fahrer werden unter Admin → Benutzer (Schritt „Tour-Zuweisung") zugeordnet.\nJede Tour-Kachel zeigt Fortschritt, Objektanzahl sowie Strecken-/Zeitschätzung und bietet Route berechnen, Fokussieren und Löschen.' },
      { title: 'Routenberechnung & Betriebshof', keywords: ['route', 'berechnen', 'reihenfolge', 'ors', 'betriebshof', 'depot', 'optimierung'],
        text: '„Route berechnen" ermittelt die Fahr-Reihenfolge einer Tour:\n• Standard: Luftlinien-Optimierung (ohne API-Key).\n• Mit ORS-API-Key (Admin → Allgemein): echte Straßenrouten und Fahrzeiten-Optimierung.\n• Der Betriebshof (Einstellungen) dient als Start-/Endpunkt; Modus „Rundfahrt" oder „nur Hinfahrt" wählbar.\nBerechnete Routen werden gespeichert und in Desktop- und Fahrer-App angezeigt.' },
      { title: 'Tour-Simulation', keywords: ['simulation', 'simulieren', 'tempo', 'abspielen', 'test'],
        text: 'Bei aktiver Tour lässt sich die Abarbeitung simulieren (Karten-Button): Ein Fahrzeug-Symbol fährt die Route ab.\n• Tempo-Regler 1–200×.\n• „Tätigkeit überspringen" lässt die Tätigkeits-Stopps aus (nur Fahrt).' },
      { imgs:[{src:'/handbuch/desktop-controlling.jpg',cap:'Controlling: KPIs, Diagramme und Meldungs-Tabelle'}], title: 'Controlling', keywords: ['controlling', 'auswertung', 'kpi', 'export', 'csv', 'zeitraum', 'meldungen', 'abgeschlossene touren'],
        text: 'Auswertung → Controlling zeigt für einen wählbaren Zeitraum: KPIs (erledigt / nicht erledigt / Quote), Diagramme (Status, Gründe, Zeitverlauf) und die Detail-Tabelle aller Meldungen mit Suche und CSV-Export.\nDatenbasis sind abgeschlossene Touren; Einträge lassen sich nachträglich korrigieren. Die Liste „Abgeschlossene Touren" zeigt jede Tour mit Datum, Fahrer und Ergebnis (CSV-Export je Tour).' },
      { title: 'Dashboard', keywords: ['dashboard', 'übersicht', 'karte nicht erledigt'],
        text: 'Auswertung → Dashboard: kompakte Übersicht mit Kennzahlen, Fortschritt je Tour und einer Karte aller „nicht erledigt"-Meldungen im Zeitraum.' },
      { title: 'KI-Analysen', keywords: ['ki', 'gemini', 'analyse', 'prompt', 'künstliche intelligenz', 'zeitraum', 'bericht', 'pdf', 'word', 'export'],
        text: 'Auswertung → KI-Analysen bietet vorbereitete Auswertungen (z. B. Ausfallanalyse, Management-Bericht). Im Dialog zuerst den Auswertungszeitraum wählen (7/30 Tage, Monat, gesamt oder eigener Zeitraum) — die Meldungsdaten im Prompt werden entsprechend gefiltert.\n• Manuell: fertigen Prompt kopieren und in einen KI-Dienst einfügen.\n• Automatisch: Antwort direkt in der App über Google Gemini — formatiert dargestellt, und per Klick als Bericht exportierbar: „Bericht als PDF" (Druckdialog → als PDF speichern) oder „Als Word" (.doc zum Weiterbearbeiten). Der Bericht enthält Deckkopf mit Stadt, Zeitraum und Datum.\nDer Modus wird je Stadt unter Admin → KI-Analyse festgelegt (Aus / Manuell / Automatisch / Beide). Hinweis: Die Projektdaten sind im Prompt enthalten.' },
      { imgs:[{src:'/handbuch/desktop-benutzer.jpg',cap:'Benutzerverwaltung: Rollen, Personen mit PIN, Stadt-Code'}], title: 'Benutzerverwaltung (Personen, PIN, Rollen)', keywords: ['benutzer', 'person', 'fahrer anlegen', 'pin setzen', 'rolle ändern', 'deaktivieren', 'e-mail konto'],
        text: 'Admin → Benutzer, gegliedert in Schritte:\n• Rollen: eigene Rollen mit Modulfreigaben definieren.\n• Personen (Name + PIN): anlegen, PIN setzen, Rolle ändern, deaktivieren, löschen. Hier wird auch der Stadt-Code der Stadt gepflegt.\n• E-Mail-Konten: Admin-/Planer-Zugänge mit Passwort anlegen, Rolle und Aktiv-Status verwalten.\n• Tour-Zuweisung: Fahrer den Touren eines Projekts zuordnen.' },
      { title: 'Stadt-Code ändern', keywords: ['stadt-code', 'code ändern', 'kürzel'],
        text: 'Der Stadt-Code (Kürzel der Stadt, z. B. RUESSEL) wird unter Admin → Benutzer im Personen-Bereich gepflegt. Er ist nur als Fallback nötig, wenn Name+PIN in mehreren Städten identisch sind. Format: 2–12 Zeichen, A–Z und 0–9; muss eindeutig über alle Städte sein.' },
      { title: 'Nutzung je Stadt', keywords: ['nutzung', 'reads', 'writes', 'kosten', 'verbrauch', 'monat'],
        text: 'Admin → Nutzung je Stadt zeigt die monatlichen Datenbank-Vorgänge (Lese-/Schreib-/Löschvorgänge) pro Stadt — als Näherung für die Kostenzuordnung, mit CSV-Export. Superadmin sieht alle Städte, Stadt-Admins ihre eigene.' },
      { title: 'Einstellungen (Projekt)', keywords: ['einstellungen', 'betriebshof', 'adresse', 'zeitaufwand', 'dauer', 'reihenfolgeplanung', 'depot'],
        text: 'Zahnrad oben rechts: Betriebshof (Adresse suchen oder auf Karte setzen), Depot-Modus (Rundfahrt/Hinfahrt), Routen-Optimierungsart, Zeitaufwand pro Objekt (für Zeitschätzungen) und Reihenfolgeplanung ein/aus.\nHier werden auch die WMS-Kartenebenen verwaltet.' },
      { title: 'WMS-Kartenebenen', keywords: ['wms', 'luftbild', 'kataster', 'kartenebene', 'layer', 'orthofoto'],
        text: 'Eigene Kartendienste (z. B. Luftbild, Liegenschaftskataster des Bundeslands) lassen sich als WMS-Ebenen einbinden (Einstellungen → WMS): Name, Dienst-URL und Layer-Name eintragen.\nDie Ebenen gelten stadtweit und erscheinen im Ebenen-Umschalter oben rechts auf der Karte.' },
      { title: 'ORS-API-Key (Straßen-Routing)', keywords: ['ors', 'api-key', 'openrouteservice', 'routing', 'schlüssel'],
        text: 'Für echte Straßenrouten wird ein kostenloser OpenRouteService-Key benötigt (openrouteservice.org). Eintragen unter Admin → Allgemein — der Key gilt für die ganze Stadt.' },
      { title: 'Feldbezeichnungen anpassen', keywords: ['feldbezeichnung', 'label', 'umbenennen', 'felder'],
        text: 'Admin → Feldbezeichnungen: Die Beschriftungen der Objektfelder (z. B. „Anlage/Straße", „Typ/Art") lassen sich je Projekt umbenennen — überall in der Oberfläche wirksam.' },
      { title: 'Projekte verwalten', keywords: ['projekt anlegen', 'projekt löschen', 'umbenennen'],
        text: 'Admin → Projekte: Projekte anlegen, umbenennen und löschen (Löschen erfordert Bestätigung und entfernt alle Objekte des Projekts endgültig).' },
    ],
  },
  {
    app: 'Fahrer-App (mobil)',
    icon: '🚿',
    sections: [
      { title: 'Anmeldung & Tour-Wahl', keywords: ['fahrer', 'login', 'tour wählen', 'mobil'],
        text: 'Mit Name + PIN anmelden. Sind einem mehrere Touren zugeordnet (oder keine fest zugewiesen), erscheint die Tour-Auswahl. Die zuletzt genutzte Sitzung wird gemerkt — die App startet direkt in der laufenden Tour.' },
      { imgs:[{src:'/handbuch/mobil-karte.jpg',cap:'Fahrer-App: Karte mit Route, Status-Markern und „Nächstes Objekt"-Leiste'}], title: 'Karten-Ansicht & Navigation', keywords: ['karte', 'gps', 'nächstes objekt', 'route', 'standort'],
        text: 'Die Karte zeigt die Tour-Route, alle Objekte mit Status-Farben und den eigenen GPS-Standort.\nDie Leiste „Nächstes Objekt" führt zum nächsten offenen Objekt; Antippen öffnet dessen Detail.' },
      { imgs:[{src:'/handbuch/mobil-liste.jpg',cap:'Fahrer-App: Objektliste in Fahr-Reihenfolge'}], title: 'Listen-Ansicht', keywords: ['liste', 'status punkte', 'suche', 'reihenfolge'],
        text: 'Die Liste zeigt alle Objekte der Tour in Fahr-Reihenfolge mit Status-Punkt (grün = erledigt, rot = nicht erledigt, grau = offen) und Suchfeld.' },
      { imgs:[{src:'/handbuch/mobil-detail.jpg',cap:'Melde-Dialog mit Status, Grund-Auswahl und Eigenschaften'}], title: 'Objekt melden (erledigt / nicht erledigt)', keywords: ['melden', 'status', 'erledigt', 'grund', 'bemerkung', 'nicht erledigt'],
        text: 'Objekt antippen → Status „Erledigt" oder „Nicht erledigt" wählen.\n• Bei „Nicht erledigt" einen Grund antippen (Gründe pflegt der Admin im Desktop) und optional eine Bemerkung ergänzen.\n• Zustand, Bedarf und Notiz des Objekts können direkt mit erfasst werden.' },
      { title: 'Tour abschließen / neu starten', keywords: ['abschluss', 'tour beenden', 'neu starten', 'zurücksetzen'],
        text: '„Tour abschließen" überträgt alle Meldungen als Abschluss-Bericht (erscheint im Controlling) und setzt die Tour zurück für den nächsten Durchgang.\n„Tour neu starten" setzt alle Status auf offen, ohne einen Bericht zu erzeugen.' },
      { title: 'Offline arbeiten', keywords: ['offline', 'kein netz', 'synchronisation', 'warteschlange', 'funkloch'],
        text: 'Die App funktioniert ohne Netz: Meldungen werden lokal gespeichert und automatisch übertragen, sobald wieder Verbindung besteht. Das Offline-Symbol zeigt die Anzahl ausstehender Meldungen.' },
    ],
  },
  {
    app: 'Navi-App',
    icon: '🧭',
    sections: [
      { title: 'Zweck & Bedienung', keywords: ['navi', 'navigation', 'fahren', 'sprachansage'],
        text: 'Die Navi-App ist die fahr-orientierte Variante der Fahrer-App: großes Kartenbild, automatisches Folgen der berechneten Route von Station zu Station und dieselben Melde-Funktionen (erledigt / nicht erledigt mit Grund).\nAnmeldung und Offline-Verhalten entsprechen der Fahrer-App.' },
    ],
  },
  {
    app: 'Erfassungs-App',
    icon: '📍',
    sections: [
      { title: 'Zweck & Modi', keywords: ['erfassung', 'vor ort', 'modi', 'koordinaten', 'neues objekt'],
        text: 'Die Erfassungs-App dient der Vor-Ort-Aufnahme von Objekten in zwei Modi:\n• „Koordinaten": bestehenden Objekten ohne GPS eine Position geben.\n• „Neu": komplett neue Objekte anlegen.\nDie Übersicht zeigt die eigene Tagesleistung auf der Karte.' },
      { imgs:[{src:'/handbuch/erfassung-koord.jpg',cap:'Erfassung: Liste der Objekte ohne Koordinaten'}], title: 'Koordinaten nacherfassen', keywords: ['koordinate', 'position', 'gps setzen', 'fadenkreuz', 'ohne koordinaten'],
        text: 'Reiter „Koordinaten": Liste aller Objekte ohne Position (mit Suche). Objekt antippen → Karte zentrieren (GPS-Button nutzt den eigenen Standort), Fadenkreuz auf die Stelle schieben → „Position speichern".\nDie Liste aktualisiert sich live — Objekte, die Kollegen gerade koordinieren, verschwinden automatisch.\nÜber „Eigenschaften" lassen sich dabei auch Stammdaten und Fotos ergänzen.' },
      { imgs:[{src:'/handbuch/erfassung-neu.jpg',cap:'Erfassung: Formular Neues Objekt mit Foto-Aufnahme'}], title: 'Neues Objekt anlegen', keywords: ['neu', 'anlegen', 'erfassen', 'formular'],
        text: 'Reiter „Neu": Karte auf den Standort schieben (GPS-Button hilft) → „Erfassen" → Formular ausfüllen (Name ist Pflicht; Zustand/Bedarf vorbelegt) → Speichern.\nJedes neue Objekt erhält automatisch eine Objekt-ID und erscheint sofort grün auf der Karte.' },
      { title: 'Fotos aufnehmen', keywords: ['foto', 'kamera', 'bild', 'aufnehmen', 'nacherfassen'],
        text: '„📷 Foto aufnehmen" gibt es im Neues-Objekt-Formular und in beiden „Eigenschaften bearbeiten"-Dialogen (Fotos lassen sich also auch nachträglich ergänzen).\n• Mehrere Fotos möglich; Vorschau mit Entfernen-Button vor dem Speichern.\n• Bilder werden automatisch verkleinert/komprimiert und sind danach im Desktop-Planer am Objekt sichtbar.\n• Auch offline: Fotos werden zwischengespeichert und später hochgeladen.' },
      { title: 'Übersicht & Bestandsobjekte', keywords: ['übersicht', 'bestand', 'karte leeren', 'tagesleistung'],
        text: 'Reiter „Übersicht": grüne Marker = heute neu erfasst, blaue = koordiniert. „Bestandsobjekte anzeigen" blendet alle übrigen Objekte rot ein (antippen → Eigenschaften bearbeiten).\n„Karte leeren" entfernt die eigenen Erfassungs-Markierungen aus der Übersicht — die Objekte selbst bleiben erhalten.' },
      { title: 'Offline & App neu laden', keywords: ['offline', 'cache', 'neu laden', 'hängt', 'synchronisation'],
        text: 'Die App arbeitet offline: Neuanlagen, Koordinaten und Fotos landen in einer Warteschlange und werden bei Verbindung automatisch übertragen (Zähler im Offline-Symbol).\nFalls die App einmal hängt oder veraltete Daten zeigt: Menü → „App neu laden" leert den lokalen Cache und holt alles frisch.' },
    ],
  },
  {
    app: 'Einsatzleiter-App',
    icon: '📊',
    sections: [
      { imgs:[{src:'/handbuch/einsatzleiter.jpg',cap:'Einsatzleiter: Live-Kennzahlen und Fortschritt je Tour'}], title: 'Live-Übersicht', keywords: ['einsatzleiter', 'live', 'fortschritt', 'überwachung', 'monitor'],
        text: 'Die Einsatzleiter-App zeigt den laufenden Betrieb in Echtzeit — ohne manuelles Aktualisieren: Kennzahlen (erledigt / nicht erledigt / offen / aktive Fahrer), Fortschrittsbalken je Tour, Zeitverlauf und die häufigsten Gründe für „nicht erledigt".\nDer Zeitraum ist wählbar (heute / Woche / Monat / gesamt / eigener Zeitraum).' },
      { title: 'Karte der offenen Probleme', keywords: ['karte', 'nicht erledigt', 'ausfälle', 'gründe'],
        text: 'Eine Karte markiert alle „nicht erledigt" gemeldeten Objekte im Zeitraum — Antippen zeigt Grund, Bemerkung und Fahrer.' },
      { title: 'Abgrenzung zum Controlling', keywords: ['unterschied', 'controlling', 'abgeschlossen', 'live'],
        text: 'Der Einsatzleiter sieht den Live-Stand inklusive laufender, noch nicht abgeschlossener Touren. Das Controlling im Desktop wertet die abgeschlossenen Touren aus — beides ergänzt sich bewusst.' },
    ],
  },
];
